### ISSUE TITLE
Commandline Issue

### ISSUE THREAD

**Issue by apaala** [vanOpijnenLab/MAGenTA#4]
Hi 
I am attempting to test this software with our TnSeq test Dataset and got the following error in the calc_fitness step:

Starting: 11:16:56.980784
Done generating feature lookup: 11:16:57.771881
Read first file: 11:18:03.000280
Read second file: 11:18:41.338094
Reads:
1: + 5048023 - 4872901
2: + 4364013 - 4566853
Sites:
1: + 5048023 - 4872901
2: + 4364013 - 4566853
Cfactor 1: 1.0525179837
Cfactor 2: 0.947482016297
Done comparing mapfiles 11:19:07.034614
Genic: 0
Total: 617054

**Traceback (most recent call last):
  File "/local/projects-t2/achatterjee/magenta/tools/commandline/calc_fitness.py", line 382, in <module>
    with open(arguments.outfile2, "w") as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found**

Here is my command:

/usr/local/packages/python-2.7.14/bin/python calc_fitness.py -ref sequence.gb.txt -t1 R1_trimmed.fastq.strict.map -t2 R2_trimmed.fastq.strict.map -out calc_fitness_out_strict.csv -cutoff2 0 -b BOTTLEALL -uncol UNCOL

I appreciate your help!
Apaala

**Comment by jschreie** [comment]
hi @apaala, about a year later, I am also using Magenta and am getting the same error, it would be nice if you have figured it out or have heard back, my input is:

python2 ~/Desktop/magenta/tools/galaxy/CalculateFitnesses/calc_fitness.py -expansion 10 -b BOTTLEALL -ef 0.05 -el 0.05 -ref /home/jeremy/Desktop/Sequencing_Info/dss3_5.gbk -t1 1_TnT0_S1_collapsed.sam -t2 Tn_1_S9_collapsed.sam -out Tn_1_fitness.csv 

Starting: 12:54:43.199855

Done generating feature lookup: 12:54:43.709079

Read first file: 12:54:44.757798

Read second file: 12:54:45.356314

Reads:

1: + 0 - 4494999.0

2: + 0 - 990848.0

Sites:

1: + 0 - 396043

2: + 0 - 260961

Cfactor 1: 1.63876207266

Cfactor 2: 0.361237927343

Done comparing mapfiles 12:55:14.654855

Genic: 66014

Total: 86306

Traceback (most recent call last):
  File "/home/jeremy/Desktop/magenta/tools/galaxy/CalculateFitnesses/calc_fitness.py", line 382, in <module>
    with open(arguments.outfile2, "w") as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by patriciatran** [comment]
Hi,
I'm also having trouble with the commandline option. 
I'm using a .sam file, and it looks like it's reading it properly however, all my counts and sites being reported say 0? Has anyone seen this? 
Thanks!


```
$ python magenta/tools/galaxy/Calculate\ Fitnesses/calc_fitness.py -b BOTTLEALL -wig T0_vs_T1.wig -ref genomic.gbff -t1 T0.sam -t2 T1.sam -out T0_vs_T1.csv

Starting: 10:38:48.656436

Done generating feature lookup: 10:38:49.789046

Read first file: 10:39:39.052770

Read second file: 10:40:24.335012

Reads:

1: + 0 - 0

2: + 0 - 0

Sites:

1: + 0 - 0

2: + 0 - 0

Traceback (most recent call last):
  File "magenta/tools/galaxy/Calculate Fitnesses/calc_fitness.py", line 257, in <module>
    cfactor1 = float(arguments.reads1)/total
ZeroDivisionError: float division by zero
```

I did `head -n 5` on my SAM files and they look fine. I see the # of reads per location, so I don't think the script should be reporting zeros everywhere.
